No funciona, salta error en el build de mysql
et12alumno@lab20-08:~/HospedApp$ docker-compose up -d
Building db
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  58.88kB
Step 1/4 : FROM mysql:latest
Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: read udp 127.0.0.1:33637->127.0.0.53:53: i/o timeout
ERROR: Service 'db' failed to build : Build failed